### ISSUE TITLE
Not extracting strings with backticks or backslashes?

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/strings#1] opened 2020-04-18 19:54 UTC
### Problem

I [have some pug](https://github.com/okTurtles/group-income-simple/pull/900/files) that looks like this:

```pug
      i18n.has-text-1(
        @click='handleIncomeClick'
        :args='{ \
          r1: `<button class="link js-btnInvite" data-test="openIncomeDetailsModal">`, \
          r2: "</button>" \
        }'
      ) You can change this at any time by updating your {r1}income details{r2}.
```

Running `./strings.exe frontend` doesn't extract `You can change this at any time by updating your {r1}income details{r2}.` into the `english.strings` or `english.json` file (or any of the files).

### Solution

Figure out why and update parser to handle? Or if I'm doing something wrong, update instructions to make it clearer what I'm supposed to do?

**Comment by SGrondin** [comment] 2020-04-19 21:06
Fixed in 1.0.3.

The issue you found was due to the parser only extracting strings from `i18n` elements, strictly. Not `i18n.has-text-1`, only `i18n`.

After fixing it, I also noticed that it wasn't capturing `L(...)` when it was in a Pug node text, such as `Payments` here: https://github.com/okTurtles/group-income-simple/blob/d4beeffef59e637f0944a7ba4ecade87f73b5bc2/frontend/views/pages/Payments.vue#L8
It was only capturing `L(...)` in node attributes.

Both have been fixed in [v1.0.3](https://github.com/okTurtles/strings/releases/tag/v1.0.3) and I validated that no translations were lost due to this change (no regressions).

**Closed by SGrondin** 2020-04-19 21:06 UTC
